
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos2 {
  /* terminals */
  public static final int frase = 2;
  public static final int o = 3;
  public static final int EOF = 0;
  public static final int punto = 5;
  public static final int pregunta = 8;
  public static final int declaracion = 4;
  public static final int error = 1;
  public static final int asterisco = 7;
  public static final int mas = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "frase",
  "o",
  "declaracion",
  "punto",
  "mas",
  "asterisco",
  "pregunta"
  };
}

