
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int frase = 11;
  public static final int dos_puntos = 3;
  public static final int conjunto = 12;
  public static final int separador_region = 10;
  public static final int id = 2;
  public static final int conjpr = 4;
  public static final int cierra_llave = 9;
  public static final int EOF = 0;
  public static final int expreg = 13;
  public static final int error = 1;
  public static final int flecha = 5;
  public static final int abre_llave = 8;
  public static final int DecIntegerLiteral = 6;
  public static final int separador = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "dos_puntos",
  "conjpr",
  "flecha",
  "DecIntegerLiteral",
  "separador",
  "abre_llave",
  "cierra_llave",
  "separador_region",
  "frase",
  "conjunto",
  "expreg"
  };
}

